[package]
name = "canvastest"
version = "0.1.0"
authors = ["Arator <arator.rl@outlook.com>"]
edition = "2021"

[dependencies]
bakkesmod = { path = "../../" }

[lib]
name = "canvastest"
crate-type = ["cdylib"]